### PR TITLE
Bump build no to attempt spawning 1st official build

### PR DESCRIPTION
**Pull request by willend**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by willend** [comment]
@conda-forge-admin, please rerender

**Comment by willend** [comment]
@conda-forge-admin, please rerender

**Comment by ebknudsen** [comment]
This PR was superceeded by #2. Thanks for contributing.

**Comment by willend** [comment]
You're welcome @ebknudsen and congrats on your 1st package on conda-forge. 😉 Is it "pure python" or are there c/c++ bits? (I would guess macOS can easily be made functional irrespective...)

**Comment by ebknudsen** [comment]
This is pure python, so should indeed be reasonably simple and possible to do macOS.

**Pull request closed without merging**
